### ISSUE TITLE
Rename this crate to a more fitting identifier

### ISSUE THREAD

**Issue by Byron** [Byron/yup-oauth2#32]
The current name, `yup-oauth2` stems from the original intention to a very specialised implementation of the oauth2 protocol needed to get a **y**o**u**tube u**p**loader going.

By now, this crate has become so much more that the name seems inadequate.

@dermesser Do you agree to this premise, and if so, maybe you have some suggestions for a new name too ?

**Comment by dermesser** [comment]
I had in the back of my head the notion that it's related to `yup` -- but by now I don't think about it much more. To me it's just a short memorable name for this particular OAuth implementation, and *yup* in particular reminds me of the reaffirming sound that API servers make when they give you access :P

Anyway; I'm fine with the current name, but if you hate the name you should go ahead and change it.

**Comment by Byron** [comment]
I have indeed never seen it that way, but `yup` - you can come in, sounds like a rather fitting prefix for an oauth-crate. So I will forget the legacy origin of yup, and instead claim it 'that sound that servers make when they let you in' !
Fantastic :) !
