### ISSUE TITLE
Go v1.0.0

### ISSUE THREAD

**Issue by Byron** [Byron/yup-oauth2#33]
This crate seems to be feature-complete enough to justify the big step upwards to 1.0. Feature-wise, the most common flows are available now.

When looking at the dependencies, there are still many below 1.0, but in a way this only affects their package maintainers as they essentially lose the patch-level in their version number (for sub-1-major packages, the minor version effectively becomes the major one when computing compatibility).

@dermesser Do you think it's OK going to 1.0 soon ?

**Comment by dermesser** [comment]
Yes, I certainly think so. In general it seems that Rust developers are a bit conservative about incrementing the major version (thus all the other "immature" crates), but I'm fine with it. :-)

**Comment by Byron** [comment]
@dermesser It would mean a lot to me if you would (at some point in time) prepare the 1.0 release :) ! My recommendation is to use `clog` (like in `clog --major  -C changelog.md`) to update the changelog (maybe even give it some manual treatment afterwards), and ... that should already be it.

I shall run `cargo publish` when the PR (or commit) has landed, should you choose to set up the major release.

Personally I think it's OK to go 1.0 once 'it works', and then generously increase the major version. Something I will do for the `google-apis-rs` project to, once this one went 1.0.

**Comment by Byron** [comment]
@dermesser Considering the incredible amount of contributions you have made, and the fact that to me this crate was only a means to get my youtube uploader going somehow, it might be time consider something more drastic than just making you a contributor! Instead, I propose to swap roles ! Thus you would become the owner of this project on GitHub, I would just be a contributor sending in PRs as needed. You have a way better grasp on the entire project by now, and making you the owner would just reflect this.
Personally I would love to keep using `yup-oauth2` in the `google-apis-rs` project, and take care of that one only.

In case you are inclined to do the swap, we would have to find a way to transfer ownership on crates.io as well, which seems to be possible through direct communication with the community administrators.

What do you think ?

**Comment by dermesser** [comment]
If you don't want to put up with my PRs, you can tell it straight to my face :P

In all seriousness, I'd be honored to take over this project. I don't know either how to transfer ownership of a crate, but your idea seems reasonable. FWIW, my crates.io user name is the same as my github username (I guess that's true for every account...)

**Comment by Byron** [comment]
@dermesser I just casually tried to transfer ownership to you, but apparently that won't work until you have deleted your fork. Kind of makes sense, too. In any case, I would be glad if you could make me a contributor after the transfer is completed, so that I can help out if needed.

**Comment by Byron** [comment]
Alright, 1.0 is out.
Just let me know when you have deleted your fork, and I shall transfer ownership right away.
Thanks and cheers :).

**Comment by dermesser** [comment]
Just deleted my fork :)
