### ISSUE TITLE
Documentation link on crates.io is 404

### ISSUE THREAD

**Issue by killercup** [Byron/yup-oauth2#7]
Hi, I just noticed that on https://crates.io/crates/yup-oauth2 the documentation link is set to `http://byron.github.io/yup-oauth2`. This redirects to `http://byron.github.io/yup-oauth2/yup-oauth2/index.html`, which doesn't exist.

**Comment by Byron** [comment]
Thanks for letting me know ! It works now, and should keep working in the foreseeable future provided travis will ever manage to build the project and run `travis-cargo docs` on it.
